# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('autor', models.CharField(max_length=100)),
                ('tipo_ruta', models.CharField(max_length=100)),
                ('altrimetria_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altimetria_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desnivel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorrido_circular', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorrido_lineal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('libro_ruta', models.TextField()),
                ('detalles', models.TextField()),
            ],
        ),
    ]
