# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controlja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 16, 17, 47, 57, 738526, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
