# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlja', '0002_rutas_create_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rutas',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlja.Rutas'),
        ),
    ]
