# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlja', '0003_auto_20160623_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlja.Rutas'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='tipo_ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlja.TipoRuta'),
        ),
    ]
