# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlja', '0004_auto_20160623_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlja.Rutas')),
            ],
        ),
    ]
